/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/chung_tu": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chung_tu.id"];
          user_id?: parameters["rowFilter.chung_tu.user_id"];
          so_chung_tu?: parameters["rowFilter.chung_tu.so_chung_tu"];
          loai_chung_tu?: parameters["rowFilter.chung_tu.loai_chung_tu"];
          ngay_hach_toan?: parameters["rowFilter.chung_tu.ngay_hach_toan"];
          ngay_chung_tu?: parameters["rowFilter.chung_tu.ngay_chung_tu"];
          doi_tuong_id?: parameters["rowFilter.chung_tu.doi_tuong_id"];
          ten_doi_tuong?: parameters["rowFilter.chung_tu.ten_doi_tuong"];
          dia_chi?: parameters["rowFilter.chung_tu.dia_chi"];
          ly_do?: parameters["rowFilter.chung_tu.ly_do"];
          dien_giai_chung?: parameters["rowFilter.chung_tu.dien_giai_chung"];
          nguoi_nop?: parameters["rowFilter.chung_tu.nguoi_nop"];
          nguoi_nhan?: parameters["rowFilter.chung_tu.nguoi_nhan"];
          nhan_vien?: parameters["rowFilter.chung_tu.nhan_vien"];
          chung_tu_goc?: parameters["rowFilter.chung_tu.chung_tu_goc"];
          tk_ngan_hang?: parameters["rowFilter.chung_tu.tk_ngan_hang"];
          loai_tien?: parameters["rowFilter.chung_tu.loai_tien"];
          ty_gia?: parameters["rowFilter.chung_tu.ty_gia"];
          da_khoa?: parameters["rowFilter.chung_tu.da_khoa"];
          but_toan?: parameters["rowFilter.chung_tu.but_toan"];
          created_at?: parameters["rowFilter.chung_tu.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["chung_tu"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** chung_tu */
          chung_tu?: definitions["chung_tu"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chung_tu.id"];
          user_id?: parameters["rowFilter.chung_tu.user_id"];
          so_chung_tu?: parameters["rowFilter.chung_tu.so_chung_tu"];
          loai_chung_tu?: parameters["rowFilter.chung_tu.loai_chung_tu"];
          ngay_hach_toan?: parameters["rowFilter.chung_tu.ngay_hach_toan"];
          ngay_chung_tu?: parameters["rowFilter.chung_tu.ngay_chung_tu"];
          doi_tuong_id?: parameters["rowFilter.chung_tu.doi_tuong_id"];
          ten_doi_tuong?: parameters["rowFilter.chung_tu.ten_doi_tuong"];
          dia_chi?: parameters["rowFilter.chung_tu.dia_chi"];
          ly_do?: parameters["rowFilter.chung_tu.ly_do"];
          dien_giai_chung?: parameters["rowFilter.chung_tu.dien_giai_chung"];
          nguoi_nop?: parameters["rowFilter.chung_tu.nguoi_nop"];
          nguoi_nhan?: parameters["rowFilter.chung_tu.nguoi_nhan"];
          nhan_vien?: parameters["rowFilter.chung_tu.nhan_vien"];
          chung_tu_goc?: parameters["rowFilter.chung_tu.chung_tu_goc"];
          tk_ngan_hang?: parameters["rowFilter.chung_tu.tk_ngan_hang"];
          loai_tien?: parameters["rowFilter.chung_tu.loai_tien"];
          ty_gia?: parameters["rowFilter.chung_tu.ty_gia"];
          da_khoa?: parameters["rowFilter.chung_tu.da_khoa"];
          but_toan?: parameters["rowFilter.chung_tu.but_toan"];
          created_at?: parameters["rowFilter.chung_tu.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chung_tu.id"];
          user_id?: parameters["rowFilter.chung_tu.user_id"];
          so_chung_tu?: parameters["rowFilter.chung_tu.so_chung_tu"];
          loai_chung_tu?: parameters["rowFilter.chung_tu.loai_chung_tu"];
          ngay_hach_toan?: parameters["rowFilter.chung_tu.ngay_hach_toan"];
          ngay_chung_tu?: parameters["rowFilter.chung_tu.ngay_chung_tu"];
          doi_tuong_id?: parameters["rowFilter.chung_tu.doi_tuong_id"];
          ten_doi_tuong?: parameters["rowFilter.chung_tu.ten_doi_tuong"];
          dia_chi?: parameters["rowFilter.chung_tu.dia_chi"];
          ly_do?: parameters["rowFilter.chung_tu.ly_do"];
          dien_giai_chung?: parameters["rowFilter.chung_tu.dien_giai_chung"];
          nguoi_nop?: parameters["rowFilter.chung_tu.nguoi_nop"];
          nguoi_nhan?: parameters["rowFilter.chung_tu.nguoi_nhan"];
          nhan_vien?: parameters["rowFilter.chung_tu.nhan_vien"];
          chung_tu_goc?: parameters["rowFilter.chung_tu.chung_tu_goc"];
          tk_ngan_hang?: parameters["rowFilter.chung_tu.tk_ngan_hang"];
          loai_tien?: parameters["rowFilter.chung_tu.loai_tien"];
          ty_gia?: parameters["rowFilter.chung_tu.ty_gia"];
          da_khoa?: parameters["rowFilter.chung_tu.da_khoa"];
          but_toan?: parameters["rowFilter.chung_tu.but_toan"];
          created_at?: parameters["rowFilter.chung_tu.created_at"];
        };
        body: {
          /** chung_tu */
          chung_tu?: definitions["chung_tu"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/voucher": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.voucher.id"];
          company_id?: parameters["rowFilter.voucher.company_id"];
          voucher_no?: parameters["rowFilter.voucher.voucher_no"];
          voucher_type?: parameters["rowFilter.voucher.voucher_type"];
          cash_source?: parameters["rowFilter.voucher.cash_source"];
          txn_kind?: parameters["rowFilter.voucher.txn_kind"];
          partner_id?: parameters["rowFilter.voucher.partner_id"];
          reason?: parameters["rowFilter.voucher.reason"];
          voucher_date?: parameters["rowFilter.voucher.voucher_date"];
          posting_date?: parameters["rowFilter.voucher.posting_date"];
          attached_docs?: parameters["rowFilter.voucher.attached_docs"];
          total_amount?: parameters["rowFilter.voucher.total_amount"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["voucher"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** voucher */
          voucher?: definitions["voucher"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.voucher.id"];
          company_id?: parameters["rowFilter.voucher.company_id"];
          voucher_no?: parameters["rowFilter.voucher.voucher_no"];
          voucher_type?: parameters["rowFilter.voucher.voucher_type"];
          cash_source?: parameters["rowFilter.voucher.cash_source"];
          txn_kind?: parameters["rowFilter.voucher.txn_kind"];
          partner_id?: parameters["rowFilter.voucher.partner_id"];
          reason?: parameters["rowFilter.voucher.reason"];
          voucher_date?: parameters["rowFilter.voucher.voucher_date"];
          posting_date?: parameters["rowFilter.voucher.posting_date"];
          attached_docs?: parameters["rowFilter.voucher.attached_docs"];
          total_amount?: parameters["rowFilter.voucher.total_amount"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.voucher.id"];
          company_id?: parameters["rowFilter.voucher.company_id"];
          voucher_no?: parameters["rowFilter.voucher.voucher_no"];
          voucher_type?: parameters["rowFilter.voucher.voucher_type"];
          cash_source?: parameters["rowFilter.voucher.cash_source"];
          txn_kind?: parameters["rowFilter.voucher.txn_kind"];
          partner_id?: parameters["rowFilter.voucher.partner_id"];
          reason?: parameters["rowFilter.voucher.reason"];
          voucher_date?: parameters["rowFilter.voucher.voucher_date"];
          posting_date?: parameters["rowFilter.voucher.posting_date"];
          attached_docs?: parameters["rowFilter.voucher.attached_docs"];
          total_amount?: parameters["rowFilter.voucher.total_amount"];
        };
        body: {
          /** voucher */
          voucher?: definitions["voucher"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/ngan_hang": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ngan_hang.id"];
          user_id?: parameters["rowFilter.ngan_hang.user_id"];
          ma?: parameters["rowFilter.ngan_hang.ma"];
          ten?: parameters["rowFilter.ngan_hang.ten"];
          so_tai_khoan?: parameters["rowFilter.ngan_hang.so_tai_khoan"];
          chi_nhanh?: parameters["rowFilter.ngan_hang.chi_nhanh"];
          da_vo_hieu_hoa?: parameters["rowFilter.ngan_hang.da_vo_hieu_hoa"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ngan_hang"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ngan_hang */
          ngan_hang?: definitions["ngan_hang"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ngan_hang.id"];
          user_id?: parameters["rowFilter.ngan_hang.user_id"];
          ma?: parameters["rowFilter.ngan_hang.ma"];
          ten?: parameters["rowFilter.ngan_hang.ten"];
          so_tai_khoan?: parameters["rowFilter.ngan_hang.so_tai_khoan"];
          chi_nhanh?: parameters["rowFilter.ngan_hang.chi_nhanh"];
          da_vo_hieu_hoa?: parameters["rowFilter.ngan_hang.da_vo_hieu_hoa"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ngan_hang.id"];
          user_id?: parameters["rowFilter.ngan_hang.user_id"];
          ma?: parameters["rowFilter.ngan_hang.ma"];
          ten?: parameters["rowFilter.ngan_hang.ten"];
          so_tai_khoan?: parameters["rowFilter.ngan_hang.so_tai_khoan"];
          chi_nhanh?: parameters["rowFilter.ngan_hang.chi_nhanh"];
          da_vo_hieu_hoa?: parameters["rowFilter.ngan_hang.da_vo_hieu_hoa"];
        };
        body: {
          /** ngan_hang */
          ngan_hang?: definitions["ngan_hang"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/ho_so_doanh_nghiep": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ho_so_doanh_nghiep.id"];
          user_id?: parameters["rowFilter.ho_so_doanh_nghiep.user_id"];
          ten_dn?: parameters["rowFilter.ho_so_doanh_nghiep.ten_dn"];
          dia_chi?: parameters["rowFilter.ho_so_doanh_nghiep.dia_chi"];
          ma_so_thue?: parameters["rowFilter.ho_so_doanh_nghiep.ma_so_thue"];
          ho_ten_sinh_vien?: parameters["rowFilter.ho_so_doanh_nghiep.ho_ten_sinh_vien"];
          chuc_danh?: parameters["rowFilter.ho_so_doanh_nghiep.chuc_danh"];
          lop?: parameters["rowFilter.ho_so_doanh_nghiep.lop"];
          ky_thuc_hanh?: parameters["rowFilter.ho_so_doanh_nghiep.ky_thuc_hanh"];
          trang_thai?: parameters["rowFilter.ho_so_doanh_nghiep.trang_thai"];
          ngay_nop?: parameters["rowFilter.ho_so_doanh_nghiep.ngay_nop"];
          created_at?: parameters["rowFilter.ho_so_doanh_nghiep.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ho_so_doanh_nghiep"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ho_so_doanh_nghiep */
          ho_so_doanh_nghiep?: definitions["ho_so_doanh_nghiep"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ho_so_doanh_nghiep.id"];
          user_id?: parameters["rowFilter.ho_so_doanh_nghiep.user_id"];
          ten_dn?: parameters["rowFilter.ho_so_doanh_nghiep.ten_dn"];
          dia_chi?: parameters["rowFilter.ho_so_doanh_nghiep.dia_chi"];
          ma_so_thue?: parameters["rowFilter.ho_so_doanh_nghiep.ma_so_thue"];
          ho_ten_sinh_vien?: parameters["rowFilter.ho_so_doanh_nghiep.ho_ten_sinh_vien"];
          chuc_danh?: parameters["rowFilter.ho_so_doanh_nghiep.chuc_danh"];
          lop?: parameters["rowFilter.ho_so_doanh_nghiep.lop"];
          ky_thuc_hanh?: parameters["rowFilter.ho_so_doanh_nghiep.ky_thuc_hanh"];
          trang_thai?: parameters["rowFilter.ho_so_doanh_nghiep.trang_thai"];
          ngay_nop?: parameters["rowFilter.ho_so_doanh_nghiep.ngay_nop"];
          created_at?: parameters["rowFilter.ho_so_doanh_nghiep.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ho_so_doanh_nghiep.id"];
          user_id?: parameters["rowFilter.ho_so_doanh_nghiep.user_id"];
          ten_dn?: parameters["rowFilter.ho_so_doanh_nghiep.ten_dn"];
          dia_chi?: parameters["rowFilter.ho_so_doanh_nghiep.dia_chi"];
          ma_so_thue?: parameters["rowFilter.ho_so_doanh_nghiep.ma_so_thue"];
          ho_ten_sinh_vien?: parameters["rowFilter.ho_so_doanh_nghiep.ho_ten_sinh_vien"];
          chuc_danh?: parameters["rowFilter.ho_so_doanh_nghiep.chuc_danh"];
          lop?: parameters["rowFilter.ho_so_doanh_nghiep.lop"];
          ky_thuc_hanh?: parameters["rowFilter.ho_so_doanh_nghiep.ky_thuc_hanh"];
          trang_thai?: parameters["rowFilter.ho_so_doanh_nghiep.trang_thai"];
          ngay_nop?: parameters["rowFilter.ho_so_doanh_nghiep.ngay_nop"];
          created_at?: parameters["rowFilter.ho_so_doanh_nghiep.created_at"];
        };
        body: {
          /** ho_so_doanh_nghiep */
          ho_so_doanh_nghiep?: definitions["ho_so_doanh_nghiep"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/partner": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.partner.id"];
          company_id?: parameters["rowFilter.partner.company_id"];
          type?: parameters["rowFilter.partner.type"];
          code?: parameters["rowFilter.partner.code"];
          name?: parameters["rowFilter.partner.name"];
          address?: parameters["rowFilter.partner.address"];
          tax_code?: parameters["rowFilter.partner.tax_code"];
          goods_name?: parameters["rowFilter.partner.goods_name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["partner"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** partner */
          partner?: definitions["partner"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.partner.id"];
          company_id?: parameters["rowFilter.partner.company_id"];
          type?: parameters["rowFilter.partner.type"];
          code?: parameters["rowFilter.partner.code"];
          name?: parameters["rowFilter.partner.name"];
          address?: parameters["rowFilter.partner.address"];
          tax_code?: parameters["rowFilter.partner.tax_code"];
          goods_name?: parameters["rowFilter.partner.goods_name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.partner.id"];
          company_id?: parameters["rowFilter.partner.company_id"];
          type?: parameters["rowFilter.partner.type"];
          code?: parameters["rowFilter.partner.code"];
          name?: parameters["rowFilter.partner.name"];
          address?: parameters["rowFilter.partner.address"];
          tax_code?: parameters["rowFilter.partner.tax_code"];
          goods_name?: parameters["rowFilter.partner.goods_name"];
        };
        body: {
          /** partner */
          partner?: definitions["partner"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/ledger_entry": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ledger_entry.id"];
          voucher_id?: parameters["rowFilter.ledger_entry.voucher_id"];
          company_id?: parameters["rowFilter.ledger_entry.company_id"];
          posting_date?: parameters["rowFilter.ledger_entry.posting_date"];
          narration?: parameters["rowFilter.ledger_entry.narration"];
          debit_acct?: parameters["rowFilter.ledger_entry.debit_acct"];
          credit_acct?: parameters["rowFilter.ledger_entry.credit_acct"];
          amount?: parameters["rowFilter.ledger_entry.amount"];
          partner_id?: parameters["rowFilter.ledger_entry.partner_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ledger_entry"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ledger_entry */
          ledger_entry?: definitions["ledger_entry"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ledger_entry.id"];
          voucher_id?: parameters["rowFilter.ledger_entry.voucher_id"];
          company_id?: parameters["rowFilter.ledger_entry.company_id"];
          posting_date?: parameters["rowFilter.ledger_entry.posting_date"];
          narration?: parameters["rowFilter.ledger_entry.narration"];
          debit_acct?: parameters["rowFilter.ledger_entry.debit_acct"];
          credit_acct?: parameters["rowFilter.ledger_entry.credit_acct"];
          amount?: parameters["rowFilter.ledger_entry.amount"];
          partner_id?: parameters["rowFilter.ledger_entry.partner_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ledger_entry.id"];
          voucher_id?: parameters["rowFilter.ledger_entry.voucher_id"];
          company_id?: parameters["rowFilter.ledger_entry.company_id"];
          posting_date?: parameters["rowFilter.ledger_entry.posting_date"];
          narration?: parameters["rowFilter.ledger_entry.narration"];
          debit_acct?: parameters["rowFilter.ledger_entry.debit_acct"];
          credit_acct?: parameters["rowFilter.ledger_entry.credit_acct"];
          amount?: parameters["rowFilter.ledger_entry.amount"];
          partner_id?: parameters["rowFilter.ledger_entry.partner_id"];
        };
        body: {
          /** ledger_entry */
          ledger_entry?: definitions["ledger_entry"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/company": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.company.id"];
          user_id?: parameters["rowFilter.company.user_id"];
          name?: parameters["rowFilter.company.name"];
          address?: parameters["rowFilter.company.address"];
          tax_code?: parameters["rowFilter.company.tax_code"];
          student_name?: parameters["rowFilter.company.student_name"];
          class_name?: parameters["rowFilter.company.class_name"];
          period_from?: parameters["rowFilter.company.period_from"];
          period_to?: parameters["rowFilter.company.period_to"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["company"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** company */
          company?: definitions["company"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.company.id"];
          user_id?: parameters["rowFilter.company.user_id"];
          name?: parameters["rowFilter.company.name"];
          address?: parameters["rowFilter.company.address"];
          tax_code?: parameters["rowFilter.company.tax_code"];
          student_name?: parameters["rowFilter.company.student_name"];
          class_name?: parameters["rowFilter.company.class_name"];
          period_from?: parameters["rowFilter.company.period_from"];
          period_to?: parameters["rowFilter.company.period_to"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.company.id"];
          user_id?: parameters["rowFilter.company.user_id"];
          name?: parameters["rowFilter.company.name"];
          address?: parameters["rowFilter.company.address"];
          tax_code?: parameters["rowFilter.company.tax_code"];
          student_name?: parameters["rowFilter.company.student_name"];
          class_name?: parameters["rowFilter.company.class_name"];
          period_from?: parameters["rowFilter.company.period_from"];
          period_to?: parameters["rowFilter.company.period_to"];
        };
        body: {
          /** company */
          company?: definitions["company"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/nha_cung_cap": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.nha_cung_cap.id"];
          user_id?: parameters["rowFilter.nha_cung_cap.user_id"];
          ma?: parameters["rowFilter.nha_cung_cap.ma"];
          ten?: parameters["rowFilter.nha_cung_cap.ten"];
          dia_chi?: parameters["rowFilter.nha_cung_cap.dia_chi"];
          ma_so_thue?: parameters["rowFilter.nha_cung_cap.ma_so_thue"];
          ten_hang_hoa?: parameters["rowFilter.nha_cung_cap.ten_hang_hoa"];
          da_vo_hieu_hoa?: parameters["rowFilter.nha_cung_cap.da_vo_hieu_hoa"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["nha_cung_cap"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** nha_cung_cap */
          nha_cung_cap?: definitions["nha_cung_cap"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.nha_cung_cap.id"];
          user_id?: parameters["rowFilter.nha_cung_cap.user_id"];
          ma?: parameters["rowFilter.nha_cung_cap.ma"];
          ten?: parameters["rowFilter.nha_cung_cap.ten"];
          dia_chi?: parameters["rowFilter.nha_cung_cap.dia_chi"];
          ma_so_thue?: parameters["rowFilter.nha_cung_cap.ma_so_thue"];
          ten_hang_hoa?: parameters["rowFilter.nha_cung_cap.ten_hang_hoa"];
          da_vo_hieu_hoa?: parameters["rowFilter.nha_cung_cap.da_vo_hieu_hoa"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.nha_cung_cap.id"];
          user_id?: parameters["rowFilter.nha_cung_cap.user_id"];
          ma?: parameters["rowFilter.nha_cung_cap.ma"];
          ten?: parameters["rowFilter.nha_cung_cap.ten"];
          dia_chi?: parameters["rowFilter.nha_cung_cap.dia_chi"];
          ma_so_thue?: parameters["rowFilter.nha_cung_cap.ma_so_thue"];
          ten_hang_hoa?: parameters["rowFilter.nha_cung_cap.ten_hang_hoa"];
          da_vo_hieu_hoa?: parameters["rowFilter.nha_cung_cap.da_vo_hieu_hoa"];
        };
        body: {
          /** nha_cung_cap */
          nha_cung_cap?: definitions["nha_cung_cap"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/account": {
    get: {
      parameters: {
        query: {
          number?: parameters["rowFilter.account.number"];
          name?: parameters["rowFilter.account.name"];
          level?: parameters["rowFilter.account.level"];
          parent_number?: parameters["rowFilter.account.parent_number"];
          acct_class?: parameters["rowFilter.account.acct_class"];
          balance_nature?: parameters["rowFilter.account.balance_nature"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["account"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** account */
          account?: definitions["account"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          number?: parameters["rowFilter.account.number"];
          name?: parameters["rowFilter.account.name"];
          level?: parameters["rowFilter.account.level"];
          parent_number?: parameters["rowFilter.account.parent_number"];
          acct_class?: parameters["rowFilter.account.acct_class"];
          balance_nature?: parameters["rowFilter.account.balance_nature"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          number?: parameters["rowFilter.account.number"];
          name?: parameters["rowFilter.account.name"];
          level?: parameters["rowFilter.account.level"];
          parent_number?: parameters["rowFilter.account.parent_number"];
          acct_class?: parameters["rowFilter.account.acct_class"];
          balance_nature?: parameters["rowFilter.account.balance_nature"];
        };
        body: {
          /** account */
          account?: definitions["account"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/opening_balance": {
    get: {
      parameters: {
        query: {
          company_id?: parameters["rowFilter.opening_balance.company_id"];
          account_number?: parameters["rowFilter.opening_balance.account_number"];
          partner_id?: parameters["rowFilter.opening_balance.partner_id"];
          debit?: parameters["rowFilter.opening_balance.debit"];
          credit?: parameters["rowFilter.opening_balance.credit"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["opening_balance"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** opening_balance */
          opening_balance?: definitions["opening_balance"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          company_id?: parameters["rowFilter.opening_balance.company_id"];
          account_number?: parameters["rowFilter.opening_balance.account_number"];
          partner_id?: parameters["rowFilter.opening_balance.partner_id"];
          debit?: parameters["rowFilter.opening_balance.debit"];
          credit?: parameters["rowFilter.opening_balance.credit"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          company_id?: parameters["rowFilter.opening_balance.company_id"];
          account_number?: parameters["rowFilter.opening_balance.account_number"];
          partner_id?: parameters["rowFilter.opening_balance.partner_id"];
          debit?: parameters["rowFilter.opening_balance.debit"];
          credit?: parameters["rowFilter.opening_balance.credit"];
        };
        body: {
          /** opening_balance */
          opening_balance?: definitions["opening_balance"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/khach_hang": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.khach_hang.id"];
          user_id?: parameters["rowFilter.khach_hang.user_id"];
          ma?: parameters["rowFilter.khach_hang.ma"];
          ten?: parameters["rowFilter.khach_hang.ten"];
          dia_chi?: parameters["rowFilter.khach_hang.dia_chi"];
          ma_so_thue?: parameters["rowFilter.khach_hang.ma_so_thue"];
          da_vo_hieu_hoa?: parameters["rowFilter.khach_hang.da_vo_hieu_hoa"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["khach_hang"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** khach_hang */
          khach_hang?: definitions["khach_hang"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.khach_hang.id"];
          user_id?: parameters["rowFilter.khach_hang.user_id"];
          ma?: parameters["rowFilter.khach_hang.ma"];
          ten?: parameters["rowFilter.khach_hang.ten"];
          dia_chi?: parameters["rowFilter.khach_hang.dia_chi"];
          ma_so_thue?: parameters["rowFilter.khach_hang.ma_so_thue"];
          da_vo_hieu_hoa?: parameters["rowFilter.khach_hang.da_vo_hieu_hoa"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.khach_hang.id"];
          user_id?: parameters["rowFilter.khach_hang.user_id"];
          ma?: parameters["rowFilter.khach_hang.ma"];
          ten?: parameters["rowFilter.khach_hang.ten"];
          dia_chi?: parameters["rowFilter.khach_hang.dia_chi"];
          ma_so_thue?: parameters["rowFilter.khach_hang.ma_so_thue"];
          da_vo_hieu_hoa?: parameters["rowFilter.khach_hang.da_vo_hieu_hoa"];
        };
        body: {
          /** khach_hang */
          khach_hang?: definitions["khach_hang"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tai_khoan_ke_toan": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tai_khoan_ke_toan.id"];
          user_id?: parameters["rowFilter.tai_khoan_ke_toan.user_id"];
          so_hieu?: parameters["rowFilter.tai_khoan_ke_toan.so_hieu"];
          ten_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.ten_tai_khoan"];
          du_no_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_no_dau_ky"];
          du_co_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_co_dau_ky"];
          loai_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.loai_tai_khoan"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tai_khoan_ke_toan"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tai_khoan_ke_toan */
          tai_khoan_ke_toan?: definitions["tai_khoan_ke_toan"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tai_khoan_ke_toan.id"];
          user_id?: parameters["rowFilter.tai_khoan_ke_toan.user_id"];
          so_hieu?: parameters["rowFilter.tai_khoan_ke_toan.so_hieu"];
          ten_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.ten_tai_khoan"];
          du_no_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_no_dau_ky"];
          du_co_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_co_dau_ky"];
          loai_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.loai_tai_khoan"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tai_khoan_ke_toan.id"];
          user_id?: parameters["rowFilter.tai_khoan_ke_toan.user_id"];
          so_hieu?: parameters["rowFilter.tai_khoan_ke_toan.so_hieu"];
          ten_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.ten_tai_khoan"];
          du_no_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_no_dau_ky"];
          du_co_dau_ky?: parameters["rowFilter.tai_khoan_ke_toan.du_co_dau_ky"];
          loai_tai_khoan?: parameters["rowFilter.tai_khoan_ke_toan.loai_tai_khoan"];
        };
        body: {
          /** tai_khoan_ke_toan */
          tai_khoan_ke_toan?: definitions["tai_khoan_ke_toan"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/app_user": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.app_user.id"];
          username?: parameters["rowFilter.app_user.username"];
          password?: parameters["rowFilter.app_user.password"];
          role?: parameters["rowFilter.app_user.role"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app_user"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** app_user */
          app_user?: definitions["app_user"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.app_user.id"];
          username?: parameters["rowFilter.app_user.username"];
          password?: parameters["rowFilter.app_user.password"];
          role?: parameters["rowFilter.app_user.role"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.app_user.id"];
          username?: parameters["rowFilter.app_user.username"];
          password?: parameters["rowFilter.app_user.password"];
          role?: parameters["rowFilter.app_user.role"];
        };
        body: {
          /** app_user */
          app_user?: definitions["app_user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  chung_tu: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    so_chung_tu?: string;
    /** Format: text */
    loai_chung_tu?: string;
    /** Format: text */
    ngay_hach_toan?: string;
    /** Format: text */
    ngay_chung_tu?: string;
    /** Format: uuid */
    doi_tuong_id?: string;
    /** Format: text */
    ten_doi_tuong?: string;
    /** Format: text */
    dia_chi?: string;
    /** Format: text */
    ly_do?: string;
    /** Format: text */
    dien_giai_chung?: string;
    /** Format: text */
    nguoi_nop?: string;
    /** Format: text */
    nguoi_nhan?: string;
    /** Format: text */
    nhan_vien?: string;
    /** Format: text */
    chung_tu_goc?: string;
    /** Format: text */
    tk_ngan_hang?: string;
    /**
     * Format: text
     * @default VND
     */
    loai_tien?: string;
    /**
     * Format: numeric
     * @default 1
     */
    ty_gia?: number;
    /**
     * Format: boolean
     * @default false
     */
    da_khoa?: boolean;
    /** Format: jsonb */
    but_toan?: unknown;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at?: string;
  };
  voucher: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `company.id`.<fk table='company' column='id'/>
     */
    company_id: number;
    /** Format: character varying */
    voucher_no: string;
    /** Format: character varying */
    voucher_type: string;
    /** Format: character varying */
    cash_source: string;
    /** Format: character varying */
    txn_kind: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `partner.id`.<fk table='partner' column='id'/>
     */
    partner_id?: number;
    /** Format: character varying */
    reason?: string;
    /** Format: date */
    voucher_date: string;
    /** Format: date */
    posting_date: string;
    /** Format: smallint */
    attached_docs?: number;
    /** Format: numeric */
    total_amount: number;
  };
  ngan_hang: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    ma?: string;
    /** Format: text */
    ten?: string;
    /** Format: text */
    so_tai_khoan?: string;
    /** Format: text */
    chi_nhanh?: string;
    /**
     * Format: boolean
     * @default false
     */
    da_vo_hieu_hoa?: boolean;
  };
  ho_so_doanh_nghiep: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    ten_dn?: string;
    /** Format: text */
    dia_chi?: string;
    /** Format: text */
    ma_so_thue?: string;
    /** Format: text */
    ho_ten_sinh_vien?: string;
    /** Format: text */
    chuc_danh?: string;
    /** Format: text */
    lop?: string;
    /** Format: text */
    ky_thuc_hanh?: string;
    /**
     * Format: text
     * @default DANG_LAM
     */
    trang_thai?: string;
    /** Format: text */
    ngay_nop?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at?: string;
  };
  partner: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `company.id`.<fk table='company' column='id'/>
     */
    company_id: number;
    /** Format: character varying */
    type: string;
    /** Format: character varying */
    code?: string;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    address?: string;
    /** Format: character varying */
    tax_code?: string;
    /** Format: character varying */
    goods_name?: string;
  };
  ledger_entry: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `voucher.id`.<fk table='voucher' column='id'/>
     */
    voucher_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `company.id`.<fk table='company' column='id'/>
     */
    company_id: number;
    /** Format: date */
    posting_date: string;
    /** Format: character varying */
    narration?: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `account.number`.<fk table='account' column='number'/>
     */
    debit_acct: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `account.number`.<fk table='account' column='number'/>
     */
    credit_acct: string;
    /** Format: numeric */
    amount: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `partner.id`.<fk table='partner' column='id'/>
     */
    partner_id?: number;
  };
  company: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `app_user.id`.<fk table='app_user' column='id'/>
     */
    user_id: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    address?: string;
    /** Format: character varying */
    tax_code?: string;
    /** Format: character varying */
    student_name?: string;
    /** Format: character varying */
    class_name?: string;
    /** Format: date */
    period_from: string;
    /** Format: date */
    period_to: string;
  };
  nha_cung_cap: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    ma?: string;
    /** Format: text */
    ten?: string;
    /** Format: text */
    dia_chi?: string;
    /** Format: text */
    ma_so_thue?: string;
    /** Format: text */
    ten_hang_hoa?: string;
    /**
     * Format: boolean
     * @default false
     */
    da_vo_hieu_hoa?: boolean;
  };
  account: {
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    number: string;
    /** Format: character varying */
    name: string;
    /** Format: smallint */
    level: number;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `account.number`.<fk table='account' column='number'/>
     */
    parent_number?: string;
    /** Format: smallint */
    acct_class: number;
    /** Format: character varying */
    balance_nature: string;
  };
  opening_balance: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `company.id`.<fk table='company' column='id'/>
     */
    company_id: number;
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `account.number`.<fk table='account' column='number'/>
     */
    account_number: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `partner.id`.<fk table='partner' column='id'/>
     */
    partner_id: number;
    /** Format: numeric */
    debit: number;
    /** Format: numeric */
    credit: number;
  };
  khach_hang: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    ma?: string;
    /** Format: text */
    ten?: string;
    /** Format: text */
    dia_chi?: string;
    /** Format: text */
    ma_so_thue?: string;
    /**
     * Format: boolean
     * @default false
     */
    da_vo_hieu_hoa?: boolean;
  };
  tai_khoan_ke_toan: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default gen_random_uuid()
     */
    id: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    so_hieu?: string;
    /** Format: text */
    ten_tai_khoan?: string;
    /**
     * Format: numeric
     * @default 0
     */
    du_no_dau_ky?: number;
    /**
     * Format: numeric
     * @default 0
     */
    du_co_dau_ky?: number;
    /** Format: text */
    loai_tai_khoan?: string;
  };
  app_user: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    username: string;
    /** Format: character varying */
    password: string;
    /** Format: character varying */
    role: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: string;
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description chung_tu */
  "body.chung_tu": definitions["chung_tu"];
  "rowFilter.chung_tu.id": string;
  "rowFilter.chung_tu.user_id": string;
  "rowFilter.chung_tu.so_chung_tu": string;
  "rowFilter.chung_tu.loai_chung_tu": string;
  "rowFilter.chung_tu.ngay_hach_toan": string;
  "rowFilter.chung_tu.ngay_chung_tu": string;
  "rowFilter.chung_tu.doi_tuong_id": string;
  "rowFilter.chung_tu.ten_doi_tuong": string;
  "rowFilter.chung_tu.dia_chi": string;
  "rowFilter.chung_tu.ly_do": string;
  "rowFilter.chung_tu.dien_giai_chung": string;
  "rowFilter.chung_tu.nguoi_nop": string;
  "rowFilter.chung_tu.nguoi_nhan": string;
  "rowFilter.chung_tu.nhan_vien": string;
  "rowFilter.chung_tu.chung_tu_goc": string;
  "rowFilter.chung_tu.tk_ngan_hang": string;
  "rowFilter.chung_tu.loai_tien": string;
  "rowFilter.chung_tu.ty_gia": string;
  "rowFilter.chung_tu.da_khoa": string;
  "rowFilter.chung_tu.but_toan": string;
  "rowFilter.chung_tu.created_at": string;
  /** @description voucher */
  "body.voucher": definitions["voucher"];
  "rowFilter.voucher.id": string;
  "rowFilter.voucher.company_id": string;
  "rowFilter.voucher.voucher_no": string;
  "rowFilter.voucher.voucher_type": string;
  "rowFilter.voucher.cash_source": string;
  "rowFilter.voucher.txn_kind": string;
  "rowFilter.voucher.partner_id": string;
  "rowFilter.voucher.reason": string;
  "rowFilter.voucher.voucher_date": string;
  "rowFilter.voucher.posting_date": string;
  "rowFilter.voucher.attached_docs": string;
  "rowFilter.voucher.total_amount": string;
  /** @description ngan_hang */
  "body.ngan_hang": definitions["ngan_hang"];
  "rowFilter.ngan_hang.id": string;
  "rowFilter.ngan_hang.user_id": string;
  "rowFilter.ngan_hang.ma": string;
  "rowFilter.ngan_hang.ten": string;
  "rowFilter.ngan_hang.so_tai_khoan": string;
  "rowFilter.ngan_hang.chi_nhanh": string;
  "rowFilter.ngan_hang.da_vo_hieu_hoa": string;
  /** @description ho_so_doanh_nghiep */
  "body.ho_so_doanh_nghiep": definitions["ho_so_doanh_nghiep"];
  "rowFilter.ho_so_doanh_nghiep.id": string;
  "rowFilter.ho_so_doanh_nghiep.user_id": string;
  "rowFilter.ho_so_doanh_nghiep.ten_dn": string;
  "rowFilter.ho_so_doanh_nghiep.dia_chi": string;
  "rowFilter.ho_so_doanh_nghiep.ma_so_thue": string;
  "rowFilter.ho_so_doanh_nghiep.ho_ten_sinh_vien": string;
  "rowFilter.ho_so_doanh_nghiep.chuc_danh": string;
  "rowFilter.ho_so_doanh_nghiep.lop": string;
  "rowFilter.ho_so_doanh_nghiep.ky_thuc_hanh": string;
  "rowFilter.ho_so_doanh_nghiep.trang_thai": string;
  "rowFilter.ho_so_doanh_nghiep.ngay_nop": string;
  "rowFilter.ho_so_doanh_nghiep.created_at": string;
  /** @description partner */
  "body.partner": definitions["partner"];
  "rowFilter.partner.id": string;
  "rowFilter.partner.company_id": string;
  "rowFilter.partner.type": string;
  "rowFilter.partner.code": string;
  "rowFilter.partner.name": string;
  "rowFilter.partner.address": string;
  "rowFilter.partner.tax_code": string;
  "rowFilter.partner.goods_name": string;
  /** @description ledger_entry */
  "body.ledger_entry": definitions["ledger_entry"];
  "rowFilter.ledger_entry.id": string;
  "rowFilter.ledger_entry.voucher_id": string;
  "rowFilter.ledger_entry.company_id": string;
  "rowFilter.ledger_entry.posting_date": string;
  "rowFilter.ledger_entry.narration": string;
  "rowFilter.ledger_entry.debit_acct": string;
  "rowFilter.ledger_entry.credit_acct": string;
  "rowFilter.ledger_entry.amount": string;
  "rowFilter.ledger_entry.partner_id": string;
  /** @description company */
  "body.company": definitions["company"];
  "rowFilter.company.id": string;
  "rowFilter.company.user_id": string;
  "rowFilter.company.name": string;
  "rowFilter.company.address": string;
  "rowFilter.company.tax_code": string;
  "rowFilter.company.student_name": string;
  "rowFilter.company.class_name": string;
  "rowFilter.company.period_from": string;
  "rowFilter.company.period_to": string;
  /** @description nha_cung_cap */
  "body.nha_cung_cap": definitions["nha_cung_cap"];
  "rowFilter.nha_cung_cap.id": string;
  "rowFilter.nha_cung_cap.user_id": string;
  "rowFilter.nha_cung_cap.ma": string;
  "rowFilter.nha_cung_cap.ten": string;
  "rowFilter.nha_cung_cap.dia_chi": string;
  "rowFilter.nha_cung_cap.ma_so_thue": string;
  "rowFilter.nha_cung_cap.ten_hang_hoa": string;
  "rowFilter.nha_cung_cap.da_vo_hieu_hoa": string;
  /** @description account */
  "body.account": definitions["account"];
  "rowFilter.account.number": string;
  "rowFilter.account.name": string;
  "rowFilter.account.level": string;
  "rowFilter.account.parent_number": string;
  "rowFilter.account.acct_class": string;
  "rowFilter.account.balance_nature": string;
  /** @description opening_balance */
  "body.opening_balance": definitions["opening_balance"];
  "rowFilter.opening_balance.company_id": string;
  "rowFilter.opening_balance.account_number": string;
  "rowFilter.opening_balance.partner_id": string;
  "rowFilter.opening_balance.debit": string;
  "rowFilter.opening_balance.credit": string;
  /** @description khach_hang */
  "body.khach_hang": definitions["khach_hang"];
  "rowFilter.khach_hang.id": string;
  "rowFilter.khach_hang.user_id": string;
  "rowFilter.khach_hang.ma": string;
  "rowFilter.khach_hang.ten": string;
  "rowFilter.khach_hang.dia_chi": string;
  "rowFilter.khach_hang.ma_so_thue": string;
  "rowFilter.khach_hang.da_vo_hieu_hoa": string;
  /** @description tai_khoan_ke_toan */
  "body.tai_khoan_ke_toan": definitions["tai_khoan_ke_toan"];
  "rowFilter.tai_khoan_ke_toan.id": string;
  "rowFilter.tai_khoan_ke_toan.user_id": string;
  "rowFilter.tai_khoan_ke_toan.so_hieu": string;
  "rowFilter.tai_khoan_ke_toan.ten_tai_khoan": string;
  "rowFilter.tai_khoan_ke_toan.du_no_dau_ky": string;
  "rowFilter.tai_khoan_ke_toan.du_co_dau_ky": string;
  "rowFilter.tai_khoan_ke_toan.loai_tai_khoan": string;
  /** @description app_user */
  "body.app_user": definitions["app_user"];
  "rowFilter.app_user.id": string;
  "rowFilter.app_user.username": string;
  "rowFilter.app_user.password": string;
  "rowFilter.app_user.role": string;
}

export interface operations {}

export interface external {}
